### ISSUE TITLE
i dont understand the output. Why there are NN in left and right sequence?

### ISSUE THREAD

**Issue by Subhajeet1997** [bvalot/panISa#7]
Chromosome      End position    End clipped reads       Direct repeats  Start position  Start clipped reads     Inverted repeats        Left sequence   Right sequence
contig-2000003  334451  59      GTCCTGGAGC      334442  40      No IR   CAATGTCATCAACTTTGGAAATTATCCATAAATATCATATAATTAGCGCTCAAATCAGTGCATGGGAGNNGNC       NNNNNGGCCATGGCGGCTGGCTGCTTCGGGGGGCTTGCCTTGGGCAGGGCTGCAGCTTAGGTTGATGACATTG

**Comment by bvalot** [comment]
Hello,

Sequence right and left are a consensus of the reads covering this region. N means that left than 80% of reads give the same nucleotide at this position.
This parameter can be modified with the -p option.

**Comment by Subhajeet1997** [comment]
Thank you for the reply.  However, how can I tell which nucleotide is present there instead of N? My other question is that all the output are showing No IR what does it mean? They are not IS elements? How can I see the insertion of those IS elements in the context of the genome in relation to the reference genome?

**Comment by bvalot** [comment]
N is just an indication that this part of the sequence is not good enough (3' tail of reads).
No IR means only that inverse repeat have not be found, but the algorithm is not very sensitive and you must check that the sequence map IS element using companion script "IS_finder_search.py".
For the context of the insertion, you have the position in the reference genome.

**Comment by Subhajeet1997** [comment]
python ISFinder_search.py panisa. Most of the time it is showing error. 
Traceback (most recent call last):
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/sutripa/STRAP/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f48d7320880>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www-is.biotoul.fr', port=443): Max retries exceeded with url: /blast/resultatnorm.php?id=tmppsbO2g&title=test&prog=blastn (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48d7320880>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ISFinder_search.py", line 189, in <module>
    blast_output = search_ISfinder(potential_sequence)
  File "ISFinder_search.py", line 118, in search_ISfinder
    o = requests.get('https://www-is.biotoul.fr/blast/' + parser.urlres, verify=False)
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/sutripa/STRAP/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www-is.biotoul.fr', port=443): Max retries exceeded with url: /blast/resultatnorm.php?id=tmppsbO2g&title=test&prog=blastn (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48d7320880>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by bvalot** [comment]
Strange, I do some analysis today and it works.
Do you have some connection problems to internet?
How do you install panISa and what is your version?

**Comment by Subhajeet1997** [comment]
My version is panISa.py 0.1.6. I dont know may be my internet problem. Some times rarely it's working but maximum time not working. When i am trying to do with my real data it's showing error. I forgot but most probably installed using conda.

**Comment by Subhajeet1997** [comment]
Hello, is it possible that i will send my panisa result to you. You just run this step and give me the output??

**Comment by bvalot** [comment]
ok

**Comment by Subhajeet1997** [comment]
Can i get your email id? or should i upload here?

**Comment by bvalot** [comment]
My email is benoit.valot@univ-fcomte.fr

**Comment by SunWinner01** [comment]
May I ask which species you are using this software to analyze? I would like to analyze aquatic organisms and I am not sure if it will be applicable. @Subhajeet1997

**Comment by bvalot** [comment]
This is mainly design for insertion sequence in bacteria, I have no idea if it works on other cases.

**Comment by SunWinner01** [comment]
Okay, thank you very much for your reply. I want to use it for oyster. So I would like to ask, if my genetic data sequencing depth is 10X, do I use the default values or do I need to set these values based on the sequencing depth?


usage: panISa.py [options] bam
Search integrative element (IS) insertion on a genome using BAM alignment
positional arguments:
  bam Alignment on BAM/SAM format
optional arguments:
  -h, --help show this help message and exit
  -o [OUTPUT], --output [OUTPUT]
                        Return list of IS insertion by alignment,
                        default=stdout
  -q [QUALITY], --quality [QUALITY]
                        Min alignment quality value to conserve a clipped
                        read, default=20
  -m [MINIMUN], --minimun [MINIMUN]
                        Min number of clipped reads to look at IS on a
                        position, default=10
  -s [SIZE], --size [SIZE]
                        Maximun size of direct repeat region, default=20pb
  -p [PERCENTAGE], --percentage [PERCENTAGE]
                        Minimum percentage of same base to create consensus,
                        default=0.8
  -v, --version show program's version number and exit


---- Replied Message ----
| From | ***@***.***> |
| Date | 10/14/2024 14:53 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [bvalot/panISa] i dont understand the output. Why there are NN in left and right sequence? (Issue #7) |

This is mainly design for insertion sequence in bacteria, I have no idea if it works on other cases.

**Comment by bvalot** [comment]
10X seems low for this research, beacause only a small portion of read that covers the insertion was efficient.
you can decrease the -m option to 5 may be.

**Comment by SunWinner01** [comment]
Ok, thanks for the reply. Do the rest of the values use the default values?


---- Replied Message ----
| From | ***@***.***> |
| Date | 10/14/2024 18:00 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [bvalot/panISa] i dont understand the output. Why there are NN in left and right sequence? (Issue #7) |

10X seems low for this research, beacause only a small portion of read that covers the insertion was efficient.
you can decrease the -m option to 5 may be.

**Comment by bvalot** [comment]
Yes, I think

**Comment by SunWinner01** [comment]
ok  thank u~


---- Replied Message ----
| From | ***@***.***> |
| Date | 10/14/2024 19:16 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [bvalot/panISa] i dont understand the output. Why there are NN in left and right sequence? (Issue #7) |

Yes, I think

**Comment by SunWinner01** [comment]
Sorry to bother you again. I used the command you told me to process the test.bam file provided on this github website, and luckily got the result file without any errors! But when I use the same command to process my BAM file, some records appear in the nohup file. Can I ignore them? Even though these records exist, the .TE result file is still generated! If I cannot ignore it, why did this error occur? Hope to receive your reply, thank you!  @bvalot 
/bin/sh: einverted: command not found
/bin/sh: einverted: command not found
/bin/sh: einverted: command not found
/bin/sh: einverted: command not found
/bin/sh: einverted: command not found
/bin/sh: einverted: command not found
/bin/sh: einverted: command not found
/bin/sh: einverted: command not found
/bin/sh: einverted: command not found
/bin/sh: einverted: command not found
/bin/sh: einverted: command not found
/bin/sh: einverted: command not found

**Comment by bvalot** [comment]
You seems to have not install emboss package as indicated:
`sudo apt-get install python-pysam python-requests emboss`

**Comment by SunWinner01** [comment]
Hello, thank you very much for your previous answer. According to your suggestion, I have successfully run this software and got the .TE result file. I would like to ask if I can annotate ERV, LINE, and SINE based on this .TE result file? @bvalot

**Comment by bvalot** [comment]
I have no idea how to do that.? You probably need to use reconstruct sequence to search on specific web site for these elements.
